apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-health-check-ue21
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-health-check-ue21
    app.kubernetes.io/part-of: e2e-nodejs
  name: nodejs-health-check-ue21
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-health-check-ue21
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-health-check-ue21
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xost-tenant/e2e-nodejs/nodejs-health-check-ue21@sha256:c1eea70f7bea646dcfe29e4081a3c93db91f4f9ced5bca7959eea842b5ba4dd3
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
